# Generated by Django 4.2.6 on 2023-10-22 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id_r",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "typ_r",
                    models.IntegerField(
                        verbose_name=models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            to="typ_dict.id_typ",
                        )
                    ),
                ),
                ("date1_r", models.DateTimeField()),
                ("date2_r", models.DateTimeField()),
                ("days_r", models.IntegerField()),
                (
                    "id_car_r",
                    models.IntegerField(
                        verbose_name=models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE, to="car.id_car"
                        )
                    ),
                ),
                ("id_client_r", models.IntegerField()),
            ],
        ),
    ]
