# Generated by Django 4.2.6 on 2023-10-23 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_delete_protocol_delete_typ_dict"),
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id_prot",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("id_rez", models.IntegerField()),
                ("date_rez_from", models.DateTimeField()),
                ("date_rez_to", models.DateTimeField()),
                ("model", models.CharField(max_length=255)),
                ("engine", models.CharField(max_length=255)),
                ("vin", models.CharField(max_length=17)),
                ("reg_number", models.CharField(max_length=30)),
                ("color", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("person", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("adress", models.CharField(max_length=255)),
                ("nb_drive_licence", models.CharField(max_length=255)),
                ("pesel", models.IntegerField()),
                ("tel", models.CharField(max_length=255)),
                ("distans_release", models.IntegerField()),
                ("distans_return", models.IntegerField()),
                ("fuel_release", models.CharField(max_length=255)),
                ("fuel_return", models.CharField(max_length=255)),
                ("damage_release", models.CharField(max_length=1000)),
                ("damage_return", models.CharField(max_length=1000)),
                ("comment", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Typ_dict",
            fields=[
                (
                    "id_typ",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name_typ", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=100)),
                ("name_color", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="schedule",
            name="id_car_r",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cars.car"
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="typ_r",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="schedule.typ_dict"
            ),
        ),
    ]
