# Generated by Django 4.2.6 on 2023-10-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_protocol_typ_dict_alter_schedule_id_car_r_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule", old_name="typ_r", new_name="Typ_dict",
        ),
        migrations.RenameField(
            model_name="schedule", old_name="id_car_r", new_name="car",
        ),
    ]
